FROM openjdk:17-jdk-alpine as builder 
WORKDIR /app 
COPY ./pom.xml /app 
COPY ./.mvn ./.mvn 
COPY ./mvnw ./mvnw 
RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/ 
#RUN ./mvnw dependency:go-offline 
COPY ./src ./src 
RUN ./mvnw clean package -DskipTests 
FROM openjdk:17-jdk-alpine 
WORKDIR /app 
RUN apk add --no-cache netcat-openbsd
RUN mkdir ./logs 
COPY --from=builder /app/target/categorias-0.0.1-SNAPSHOT.jar . 
#EXPOSE 8081 
EXPOSE $PORT 
ENTRYPOINT ["java", "-jar", "categorias-0.0.1-SNAPSHOT.jar"]